# Generated by Django 5.0.7 on 2024-07-27 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('R', 'Recesso'), ('F', 'Feriado'), ('A', 'Aula')], max_length=1)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('usuarios_destinados', models.ManyToManyField(blank=True, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
