# Generated by Django 5.0.7 on 2024-07-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acessos', '0007_administrador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='planos_aula/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='acessos.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado', models.BooleanField(default=False)),
                ('data_verificacao', models.DateTimeField(blank=True, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='acessos.professor')),
                ('plano_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_aula.planoaula')),
            ],
        ),
    ]
