# Generated by Django 5.0.7 on 2024-07-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoprofessor',
            name='chamada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.chamada'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='chamada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.chamada'),
        ),
    ]
