# Generated by Django 5.0.7 on 2024-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AulaAvulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome_aluno', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('valor_aula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_aulas', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
