# Generated by Django 5.0.7 on 2024-07-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='link_pagamento',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='qr_code_pix',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes_pix/'),
        ),
    ]
