# Generated by Django 5.0.7 on 2024-07-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0002_aluno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
