# Generated by Django 5.0.7 on 2024-07-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0003_aluno_is_active_professor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='total_meses',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
