# Generated by Django 5.0.7 on 2024-07-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0004_aluno_total_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.ImageField(default=1, upload_to='fotos_professor/'),
            preserve_default=False,
        ),
    ]
