# Generated by Django 5.0.7 on 2024-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0006_aluno_professores_alter_professor_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
