# Generated by Django 5.0.7 on 2024-07-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0007_administrador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='professores',
            field=models.ManyToManyField(blank=True, null=True, related_name='alunos_associados', to='acessos.professor'),
        ),
    ]
