# Generated by Django 5.0.7 on 2024-07-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0008_alter_aluno_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, related_name='professores_associados', to='acessos.aluno'),
        ),
    ]
