# Generated by Django 5.0.7 on 2024-07-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0009_alter_professor_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='alunos',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='professores',
            field=models.ManyToManyField(related_name='alunos_associados', to='acessos.professor'),
        ),
    ]
