# Generated by Django 5.0.7 on 2024-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0012_remove_professor_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='alunos',
            field=models.ManyToManyField(related_name='professores_associados', to='acessos.aluno'),
        ),
    ]
